CREATE TABLE admin_users (
    id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    remember_me BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE inventory (
    inventory_id INT AUTO_INCREMENT PRIMARY KEY,  
    item_no VARCHAR(20) NOT NULL,  
    unit VARCHAR(50) NOT NULL, 
    item_name VARCHAR(50) NOT NULL, 
    item_description TEXT NOT NULL,  
    unit_cost DECIMAL(10, 2) NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  
    UNIQUE (item_no)  
);

CREATE TABLE pmaf (
    id INT AUTO_INCREMENT PRIMARY KEY,
    modality JSON NOT NULL, 
    project_title INT(11) UNSIGNED, 
    fund JSON, 
    mooe_items JSON, 
    co_amount DECIMAL(10, 2), 
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (project_title) REFERENCES ppmp_list(ppmp_id) ON DELETE CASCADE 
);
